config/routes.rb
Rails.application.routes.draw do
  resources :statics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/static.rb
class Static < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  before_action :set_static, only: [:show, :edit, :update, :destroy]

  # GET /statics
  # GET /statics.json
  def index
    @statics = Static.all
  end

  # GET /statics/1
  # GET /statics/1.json
  def show
  end

  # GET /statics/new
  def new
    @static = Static.new
  end

  # GET /statics/1/edit
  def edit
  end

  # POST /statics
  # POST /statics.json
  def create
    @static = Static.new(static_params)

    respond_to do |format|
      if @static.save
        format.html { redirect_to @static, notice: 'Static was successfully created.' }
        format.json { render :show, status: :created, location: @static }
      else
        format.html { render :new }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statics/1
  # PATCH/PUT /statics/1.json
  def update
    respond_to do |format|
      if @static.update(static_params)
        format.html { redirect_to @static, notice: 'Static was successfully updated.' }
        format.json { render :show, status: :ok, location: @static }
      else
        format.html { render :edit }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statics/1
  # DELETE /statics/1.json
  def destroy
    @static.destroy
    respond_to do |format|
      format.html { redirect_to statics_url, notice: 'Static was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static
      @static = Static.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_params
      params.fetch(:static, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChenmedMockup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/statics/_form.html.erb
<%= form_for(static) do |f| %>
  <% if static.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(static.errors.count, "error") %> prohibited this static from being saved:</h2>

      <ul>
      <% static.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statics/edit.html.erb
<h1>Editing Static</h1>

<%= render 'form', static: @static %>

<%= link_to 'Show', @static %> |
<%= link_to 'Back', statics_path %>

app/views/statics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statics</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statics.each do |static| %>
      <tr>
        <td><%= link_to 'Show', static %></td>
        <td><%= link_to 'Edit', edit_static_path(static) %></td>
        <td><%= link_to 'Destroy', static, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Static', new_static_path %>

app/views/statics/new.html.erb
<div class="chen_wrapper">

<header>
<div class="logo">
  <img src="https://www.chenmed.com/themes/chenmaster/public/img/logos/chenmed-logo.svg" alt="ChenMed">
</div>
<div class="chen_careers_wrapper">
  <div class="chen_careers">Careers<div class="chen_careers_find">
  Find a Job
  </div></div></div>
  <div class="chen_locations">Locations<div class="chen_locations_find">
  Learn More
</div>
</div></div>

<div class="chen_nav_bar">
    <ul block="block-chenmed-main-menu" base_plugin_id="system_menu_block" region="primary_menu" class="primary-nav__list">
                  <li class="primary-nav__item">
            <a href="/about-us" data-drupal-link-system-path="node/69">About Us</a>
                  </li>
              <li class="primary-nav__item">
            <a href="/news" title="News" data-drupal-link-system-path="news" class="is-active">News</a>
                  </li>
              <li class="primary-nav__item">
            <a href="/find-a-job" data-drupal-link-system-path="find-a-job">Careers</a>
                  </li>
              <li class="primary-nav__item">
            <a href="/executive-team" data-drupal-link-system-path="executive-team">Executive Team</a>
                  </li>
              <li class="primary-nav__item">
            <a href="/our-centers" data-drupal-link-system-path="our-centers">Locations</a>
                  </li>
              <li class="primary-nav__item">
            <a href="/contact" data-drupal-link-system-path="node/81">Contact Us</a>
                  </li>
            </ul>
  </div>
</div>
</div>
</header>

<div class="chen_body_container">
      <div class="chen_body_news">
      <div class="chen_body_news_content">
        <div class="chen_body_news_logo">
          News
        </div>
        <h1>ChenMed Strategically Expands Executive Team</h1>
        <p>Nulla id justo ac risus dapibus vehicula sit amet eget ipsum. Donec semper erat non ipsum viverra, vitae euismod purus convallis. Sed feugiat bibendum vestibulum. In id nisl iaculis, ornare erat ac, molestie sem. Nam ac velit ultricies, molestie sapien a, aliquet nisl. Aliquam scelerisque sed felis id bibendum. Suspendisse eu massa est. Morbi venenatis euismod augue, nec tempus est vulputate ut.</p>
          <button type="button" name="button">Read More</button>
      </div>


      <div class="chen_body_images">
        <div class="item"><img src="http://placehold.it/320x320&text=no+img" width="480" height="480" >
        </div>
      </div>
      <div class="chen_continued">

</div>
</div>

app/views/statics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_path(@static) %> |
<%= link_to 'Back', statics_path %>